#cloud-config
packages:
 - docker.io
 - docker-compose
 - certbot
write_files:
-   content: |
        version: '2'
        services:
          web:
            image: "mehneni/f9c"
            ports:
             - "443:8443"
            depends_on:
              - "redis"
            volumes:
              - /etc/letsencrypt/:/etc/letsencrypt/
            environment:
              - "F9C_DOMAIN=${F9C_DOMAIN}"
          redis:
            image: "redis"
    path: /etc/docker-compose.yml
