version: '2'
services:
  f9c:
    image: "mehneni/f9c"
    ports:
     - "443:8443"
    depends_on:
      - "redis"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
      - "F9C_DOMAIN=${F9C_DOMAIN}"
  bot:
    image: "mehneni/f9c-bot"
    depends_on:
      - "f9c"
    volumes:
      - /etc/f9c/bots:/usr/share/f9c/keys
  redis:
    image: "redis"
